# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
matrix:
  fast_finish: true
notifications:
  email: false
addons:
  apt:
    packages:
    - python3-numpy
script: docs/make.jl
